### ISSUE TITLE
could you add support for armv6l?

### ISSUE THREAD

**Issue by unixfox** [adelolmo/adguardhome-debian#1]
For ARM, currently only armv7 and armv8 are supported. Is it possible to add a precompiled .deb package for armv6?
Thank you.

**Comment by adelolmo** [comment]
@unixfox 
You could also build the package for `armv6`:
```
make VERSION=0.106.3 ARCH=armhf TAR_ARCH=armv6
```
This is not documented in the README, but it works just fine.

I'm getting lazy these days when it comes to add the debian packages to the releases, so adding even another package won't make it easier for me. So most probably I won't add the `armv6` version package.
